from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any, Dict, List


class FactType(StrEnum):
    """
    Supported fact categories generated by the
    Spatial Reasoning Engine.
    """

    COUNT = "count"
    POSITION = "position"
    DISTANCE = "distance"
    GROUP = "group"
    LAYOUT = "layout"


@dataclass(slots=True, frozen=True)
class SpatialFact:
    """
    Atomic fact generated by the Spatial Engine.

    Examples:

        chairs_count = 7

        umbrella_above_person = True

        nearest_object = "car"

        group_size = 4
    """

    fact_id: str
    fact_type: FactType
    statement: str
    value: Any
    confidence: float
    metadata: Dict[str, Any]

    def __post_init__(self) -> None:
        if not self.fact_id:
            raise ValueError(
                "fact_id cannot be empty"
            )

        if not self.statement:
            raise ValueError(
                "statement cannot be empty"
            )

        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(
                f"confidence must be within [0,1], got {self.confidence}"
            )


@dataclass(slots=True)
class SpatialFactSet:
    """
    Canonical output of the Spatial Engine.

    Produced by:
        Spatial Engine

    Consumed by:
        Reasoning Engine
    """

    schema_version: str
    facts: List[SpatialFact]

    def __post_init__(self) -> None:
        if not self.schema_version:
            raise ValueError(
                "schema_version cannot be empty"
            )

        fact_ids = {
            fact.fact_id
            for fact in self.facts
        }

        if len(fact_ids) != len(self.facts):
            raise ValueError(
                "Duplicate fact IDs detected"
            )

    @property
    def count(self) -> int:
        return len(self.facts)

    def get_fact(
        self,
        fact_id: str,
    ) -> SpatialFact:
        for fact in self.facts:
            if fact.fact_id == fact_id:
                return fact

        raise KeyError(
            f"Fact '{fact_id}' not found"
        )

    def facts_by_type(
        self,
        fact_type: FactType,
    ) -> List[SpatialFact]:
        return [
            fact
            for fact in self.facts
            if fact.fact_type == fact_type
        ]

    def highest_confidence_fact(
        self,
    ) -> SpatialFact:
        if not self.facts:
            raise ValueError(
                "SpatialFactSet is empty"
            )

        return max(
            self.facts,
            key=lambda fact: fact.confidence,
        )

    def average_confidence(
        self,
    ) -> float:
        if not self.facts:
            return 0.0

        return (
            sum(
                fact.confidence
                for fact in self.facts
            )
            / len(self.facts)
        )